const data = {
  customers: [
    { id: 1, name: "Ahmed Ali" },
    { id: 2, name: "Aya Elsayed" },
    { id: 3, name: "Mina Adel" },
    { id: 4, name: "Sarah Reda" },
    { id: 5, name: "Mohamed Sayed" },
    { id: 6, name: "Fatima Hassan" },
    { id: 7, name: "Omar Farouk" },
    { id: 8, name: "Nour Emad" },
    { id: 9, name: "Khaled Mahmoud" },
    { id: 10, name: "Laila Abdelaziz" },
  ],
  transactions: [
    {
      id: 1,
      customer_id: 1,
      date: "2022-01-01",
      amount: 1000,
      description: "Web development project",
    },
    {
      id: 2,
      customer_id: 1,
      date: "2022-01-02",
      amount: 2000,
      description: "Mobile app design",
    },
    {
      id: 3,
      customer_id: 2,
      date: "2022-01-01",
      amount: 550,
      description: "Graphic design work",
    },
    {
      id: 4,
      customer_id: 3,
      date: "2022-01-01",
      amount: 500,
      description: "Content writing",
    },
    {
      id: 5,
      customer_id: 2,
      date: "2022-01-02",
      amount: 1300,
      description: "UI/UX consultation",
    },
    {
      id: 6,
      customer_id: 4,
      date: "2022-01-01",
      amount: 750,
      description: "Social media management",
    },
    {
      id: 7,
      customer_id: 3,
      date: "2022-01-02",
      amount: 1250,
      description: "SEO optimization",
    },
    {
      id: 8,
      customer_id: 5,
      date: "2022-01-01",
      amount: 2500,
      description: "E-commerce platform development",
    },
    {
      id: 9,
      customer_id: 5,
      date: "2022-01-02",
      amount: 875,
      description: "Database management",
    },
    {
      id: 10,
      customer_id: 1,
      date: "2022-01-03",
      amount: 1500,
      description: "API integration",
    },
    {
      id: 11,
      customer_id: 6,
      date: "2022-01-01",
      amount: 950,
      description: "Logo design",
    },
    {
      id: 12,
      customer_id: 7,
      date: "2022-01-02",
      amount: 3000,
      description: "Full-stack development",
    },
    {
      id: 13,
      customer_id: 8,
      date: "2022-01-03",
      amount: 600,
      description: "Content marketing",
    },
    {
      id: 14,
      customer_id: 9,
      date: "2022-01-01",
      amount: 1800,
      description: "Cybersecurity consultation",
    },
    {
      id: 15,
      customer_id: 10,
      date: "2022-01-02",
      amount: 700,
      description: "Video editing",
    },
    {
      id: 16,
      customer_id: 6,
      date: "2022-01-03",
      amount: 1100,
      description: "Branding package",
    },
    {
      id: 17,
      customer_id: 7,
      date: "2022-01-04",
      amount: 2200,
      description: "Mobile app development",
    },
    {
      id: 18,
      customer_id: 8,
      date: "2022-01-02",
      amount: 450,
      description: "Email marketing campaign",
    },
    {
      id: 19,
      customer_id: 9,
      date: "2022-01-03",
      amount: 1600,
      description: "Network infrastructure setup",
    },
    {
      id: 20,
      customer_id: 10,
      date: "2022-01-04",
      amount: 900,
      description: "3D modeling",
    },
    {
      id: 21,
      customer_id: 1,
      date: "2022-01-04",
      amount: 1750,
      description: "Cloud migration services",
    },
    {
      id: 22,
      customer_id: 2,
      date: "2022-01-03",
      amount: 800,
      description: "Illustration project",
    },
    {
      id: 23,
      customer_id: 3,
      date: "2022-01-03",
      amount: 1400,
      description: "Technical writing",
    },
    {
      id: 24,
      customer_id: 4,
      date: "2022-01-02",
      amount: 650,
      description: "PPC campaign management",
    },
    {
      id: 25,
      customer_id: 5,
      date: "2022-01-03",
      amount: 2100,
      description: "CRM customization",
    },
  ],
};

export default data;
